## 0. Load imports

In [7]:
## imports
import pandas as pd
import numpy as np


## print multiple things from same cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## 0. Load data

In [10]:
## load data on 2020 crimes in DC
df = dc_crim_2020 = pd.read_csv("https://opendata.arcgis.com/datasets/f516e0dd7b614b088ad781b0c4002331_2.csv")
## you can assign multiple variable names to the same object
dc_crim_2020.head()
dc_crim_2020.shape
dc_crim_2020.info()

,X,Y,CCN,REPORT_DAT,SHIFT,METHOD,OFFENSE,BLOCK,XBLOCK,YBLOCK,...,BLOCK_GROUP,CENSUS_TRACT,VOTING_PRECINCT,LATITUDE,LONGITUDE,BID,START_DATE,END_DATE,OBJECTID,OCTO_RECORD_ID
0,-76.987540,38.903968,20008120,2020/01/14 15:49:55+00,DAY,OTHERS,THEFT F/AUTO,1200 - 1299 BLOCK OF NEAL STREET NE,401081.0,137345.0,...,008802 3,8802.0,Precinct 77,38.903960,-76.987537,NaN,2020/01/14 15:04:04+00,NaN,673713315,NaN
1,-77.004840,38.833739,20008192,2020/01/14 19:43:04+00,DAY,GUN,ASSAULT W/DANGEROUS WEAPON,100 - 165 BLOCK OF MISSISSIPPI AVENUE SE,399580.0,129549.0,...,009803 3,9803.0,Precinct 124,38.833731,-77.004837,NaN,2020/01/14 17:17:37+00,NaN,673713316,NaN
2,-76.999472,38.907644,20008246,2020/01/14 20:09:52+00,EVENING,OTHERS,THEFT/OTHER,400 - 499 BLOCK OF MORSE STREET NE,400046.0,137753.0,...,008803 2,8803.0,Precinct 76,38.907636,-76.999470,NaN,2020/01/10 23:00:00+00,2020/01/14 18:00:44+00,673713317,NaN
3,-76.982729,38.916480,20008501,2020/01/15 03:28:53+00,EVENING,OTHERS,THEFT/OTHER,1500 - 1599 BLOCK OF NEW YORK AVENUE NE,401498.0,138734.0,...,008803 1,8803.0,Precinct 76,38.916472,-76.982727,NaN,2020/01/15 02:31:24+00,NaN,673713318,NaN
4,-76.980077,38.917191,20009148,2020/01/16 04:12:47+00,MIDNIGHT,OTHERS,THEFT/OTHER,1600 - 1779 BLOCK OF NEW YORK AVENUE NE,401728.0,138813.0,...,008803 1,8803.0,Precinct 76,38.917184,-76.980074,NaN,2020/01/16 01:15:36+00,2020/01/16 01:19:54+00,673713319,NaN

(27931, 25)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27931 entries, 0 to 27930
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   X                     27931 non-null  float64
 1   Y                     27931 non-null  float64
 2   CCN                   27931 non-null  int64
 3   REPORT_DAT            27931 non-null  object
 4   SHIFT                 27931 non-null  object
 5   METHOD                27931 non-null  object
 6   OFFENSE               27931 non-null  object
 7   BLOCK                 27931 non-null  object
 8   XBLOCK                27931 non-null  float64
 9   YBLOCK                27931 non-null  float64
 10  WARD                  27931 non-null  int64
 11  ANC                   27931 non-null  object
 12  DISTRICT              27902 non-null  float64
 13  PSA                   27896 non-null  float64
 14  NEIGHBORHOOD_CLUSTER  27931 non-null  object
 15  BLOCK_GROUP           27930 non-null  object
 16  CENSUS_TRACT          27930 non-null  float64
 17  VOTING_PRECINCT       27931 non-null  object
 18  LATITUDE              27931 non-null  float64
 19  LONGITUDE             27931 non-null  float64
 20  BID                   4658 non-null   object
 21  START_DATE            27931 non-null  object
 22  END_DATE              24850 non-null  object
 23  OBJECTID              27931 non-null  int64
 24  OCTO_RECORD_ID        0 non-null      float64
dtypes: float64(10), int64(3), object(12)
memory usage: 5.3+ MB

In [11]:
## also just using df will concatenate all these comamnds for you so you can see it

In [12]:
%%time 
# do this for everything
df["X"].mean()

CPU times: user 496 Î¼s, sys: 893 Î¼s, total: 1.39 ms
Wall time: 774 Î¼s

-77.00704943937147

In [13]:
%%time

## cs 1 way

running_sum = 0
for x in df.X:
    running_sum += x

running_sum / df.X.shape[0]

CPU times: user 1.27 ms, sys: 20 Î¼s, total: 1.29 ms
Wall time: 1.31 ms

-77.00704943937163

#### Warm-up: Ways to add 100 to column X

In [17]:
df["X"] = df["X"] + 100

In [71]:
##big function definition
def add_100 (x):
    return x + 100

df.X.apply(add_100)


#kambda is a shorter way
add_100_to = lambda x: x + 100

#lambda functions are a way to do a function in one line

add_100_to(5)

#apply it to a full column
add_100_to(df["X"])
#OR
df.X.apply(add_100_to)

0        123.012460
1        122.995160
2        123.000528
3        123.017271
4        123.019923
            ...
27926    122.900569
27927    123.005634
27928    123.029624
27929    122.940778
27930    122.970368
Name: X, Length: 27931, dtype: float64

105

0        123.012460
1        122.995160
2        123.000528
3        123.017271
4        123.019923
            ...
27926    122.900569
27927    123.005634
27928    123.029624
27929    122.940778
27930    122.970368
Name: X, Length: 27931, dtype: float64

0        123.012460
1        122.995160
2        123.000528
3        123.017271
4        123.019923
            ...
27926    122.900569
27927    123.005634
27928    123.029624
27929    122.940778
27930    122.970368
Name: X, Length: 27931, dtype: float64

## 1. Aggregation

### Example of grouping by one variable and doing one aggregation 

**Task**: find and print the number of unique offense types (`OFFENSE`) by ward (`WARD`)

In [65]:
df

## HIS INTUTION EXAMPKES
df["OFFENSE"].nunique() #tells you the number of them directly-->its just 9

df.groupby("WARD") #groupby creates a bunch of subdata frames grouped by a certain value-->can do a for loop to extract each of these dfs

#nunique() is a function in the Python library pandas used to count the number of unique values in a Series or DataFrame
unique_off_byward = dc_crim_2020.groupby("WARD").agg({"OFFENSE":"nunique"}).reset_index()
#do reset index afterwards so that oyu have 0 again 
print(unique_off_byward)

## OR -->here basically finding the offense agg number of unique for each sub data frame (like short syntax of that for loop he did with sub_df then OFFENSE.nunique()
dc_crim_2020.groupby("WARD")["OFFENSE"].agg("nunique") #this just shows it out and its the same thing but no indices in the columbn


##WHAT IS THE DIFFERENCE-->te ine with agg({ creates a better table

,X,Y,CCN,REPORT_DAT,SHIFT,METHOD,OFFENSE,BLOCK,XBLOCK,YBLOCK,...,LATITUDE,LONGITUDE,BID,START_DATE,END_DATE,OBJECTID,OCTO_RECORD_ID,SHIFTS,OFFENSE_NOSP,START_DATE_CLEAN
0,-76.987540,38.903968,20008120,2020/01/14 15:49:55+00,daytime,OTHERS,THEFT F/AUTO,1200 - 1299 BLOCK OF NEAL STREET NE,401081.0,137345.0,...,38.903960,-76.987537,NaN,2020/01/14 15:04:04+00,NaN,673713315,NaN,daytime,THEFT_F/AUTO,2020-01-14 15:04:04+00:00
1,-77.004840,38.833739,20008192,2020/01/14 19:43:04+00,daytime,GUN,ASSAULT W/DANGEROUS WEAPON,100 - 165 BLOCK OF MISSISSIPPI AVENUE SE,399580.0,129549.0,...,38.833731,-77.004837,NaN,2020/01/14 17:17:37+00,NaN,673713316,NaN,daytime,ASSAULT_W/DANGEROUS_WEAPON,2020-01-14 17:17:37+00:00
2,-76.999472,38.907644,20008246,2020/01/14 20:09:52+00,daytime,OTHERS,THEFT/OTHER,400 - 499 BLOCK OF MORSE STREET NE,400046.0,137753.0,...,38.907636,-76.999470,NaN,2020/01/10 23:00:00+00,2020/01/14 18:00:44+00,673713317,NaN,nighttime,THEFT/OTHER,2020-01-10 23:00:00+00:00
3,-76.982729,38.916480,20008501,2020/01/15 03:28:53+00,daytime,OTHERS,THEFT/OTHER,1500 - 1599 BLOCK OF NEW YORK AVENUE NE,401498.0,138734.0,...,38.916472,-76.982727,NaN,2020/01/15 02:31:24+00,NaN,673713318,NaN,nighttime,THEFT/OTHER,2020-01-15 02:31:24+00:00
4,-76.980077,38.917191,20009148,2020/01/16 04:12:47+00,daytime,OTHERS,THEFT/OTHER,1600 - 1779 BLOCK OF NEW YORK AVENUE NE,401728.0,138813.0,...,38.917184,-76.980074,NaN,2020/01/16 01:15:36+00,2020/01/16 01:19:54+00,673713319,NaN,nighttime,THEFT/OTHER,2020-01-16 01:15:36+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27926,-77.099431,38.923051,20031083,2020/02/20 22:41:51+00,daytime,OTHERS,THEFT/OTHER,5000 - 5099 BLOCK OF MACARTHUR COURT NW,391378.0,139468.0,...,38.923043,-77.099428,NaN,2020/02/13 21:07:38+00,2020/02/20 12:00:55+00,674255559,NaN,nighttime,THEFT/OTHER,2020-02-13 21:07:38+00:00
27927,-76.994366,38.886033,20105472,2020/07/23 20:01:57+00,daytime,OTHERS,THEFT F/AUTO,800 - 899 BLOCK OF C STREET SE,400489.0,135354.0,...,38.886025,-76.994364,CAPITOL HILL,2020/07/22 20:00:24+00,2020/07/22 20:15:36+00,674255577,NaN,nighttime,THEFT_F/AUTO,2020-07-22 20:00:24+00:00
27928,-76.970376,38.896659,20118027,2020/08/18 20:21:23+00,daytime,OTHERS,THEFT/OTHER,500 - 599 BLOCK OF OKLAHOMA AVENUE NE,402570.0,136534.0,...,38.896651,-76.970374,NaN,2020/08/17 16:00:10+00,2020/08/18 19:30:53+00,674255586,NaN,nighttime,THEFT/OTHER,2020-08-17 16:00:10+00:00
27929,-77.059222,38.926646,20401320,2020/09/05 19:49:00+00,daytime,OTHERS,THEFT/OTHER,2910 - 2999 BLOCK OF GARFIELD STREET NW,394865.0,139864.0,...,38.926638,-77.059219,NaN,2020/09/04 22:00:00+00,2020/09/05 13:00:00+00,674255588,NaN,nighttime,THEFT/OTHER,2020-09-04 22:00:00+00:00
27930,-77.029632,38.906451,20089385,2020/06/17 18:01:07+00,daytime,OTHERS,THEFT F/AUTO,1200 - 1299 BLOCK OF 13TH STREET NW,397430.0,137621.0,...,38.906444,-77.029630,NaN,2020/06/17 13:25:24+00,2020/06/17 13:45:33+00,674255589,NaN,daytime,THEFT_F/AUTO,2020-06-17 13:25:24+00:00

9

   WARD  OFFENSE
0     1        9
1     2        9
2     3        8
3     4        8
4     5        9
5     6        9
6     7        9
7     8        9

WARD
1    9
2    9
3    8
4    8
5    9
6    9
7    9
8    9
Name: OFFENSE, dtype: int64

### Example of grouping by one variable and providing two summaries of the same variable

**Task**: previous showed number of offenses by ward but want to find out content of offenses in each ward; create an aggregation that summarizes both the number of unique offenses by ward and what those offenses are -- for instance, by pasting the unique offenses in that ward separated by the ";" (e.g., Theft; Burglary;...)

*Hint*: you can use the join command to paste together a list separated by some delimiter. 
    - The syntax, if we are using the comma delimiter, is: ", ".join(nameoflist)

In [67]:
off_byward_type = dc_crim_2020.groupby("WARD")["OFFENSE"].apply("; ".join).reset_index() #BUT THIS HAS ALL OF THEM, NOT JUST THE UNIQUE ONES
#grouping by ward-->for each ward selecting only the offense column-->fir each of these groups you are joining them into a single string separated by "; "
#apply can run it along an axis -->so here im assuming it runs it along the offense list


unique_off_byward_type = df.groupby("WARD").agg({"OFFENSE": ["nunique", lambda x: "; ".join(sorted(x.unique())
                                                                                )]}).reset_index()
                                                            #lambda function is using the syntax of joining things in a list after first finding the unique offenses and sorting them
unique_off_byward_type.columns = ["WARD", "unique_offense_count", "offense_list"]

#grouping by ward then aggrweggating by offense wihtin each group USING MULTIPLE METHODS --> bc you are doing nunique plus the join
#first computes the number of unique offenses within each ward group
#x.unique returns the number of unique offenses
#"; ".join(...) glues them together (does the concatenation with ; )
#then with rest index you move ward back into the ward columna dn have the normal indices back



print(unique_off_byward_type)

   WARD  unique_offense_count  \
0     1                     9
1     2                     9
2     3                     8
3     4                     8
4     5                     9
5     6                     9
6     7                     9
7     8                     9

                                        offense_list
0  ARSON; ASSAULT W/DANGEROUS WEAPON; BURGLARY; H...
1  ARSON; ASSAULT W/DANGEROUS WEAPON; BURGLARY; H...
2  ASSAULT W/DANGEROUS WEAPON; BURGLARY; HOMICIDE...
3  ASSAULT W/DANGEROUS WEAPON; BURGLARY; HOMICIDE...
4  ARSON; ASSAULT W/DANGEROUS WEAPON; BURGLARY; H...
5  ARSON; ASSAULT W/DANGEROUS WEAPON; BURGLARY; H...
6  ARSON; ASSAULT W/DANGEROUS WEAPON; BURGLARY; H...
7  ARSON; ASSAULT W/DANGEROUS WEAPON; BURGLARY; H...

### Example of grouping by two variables 

**Task**: group by ward (`WARD`) and police shift (`SHIFT`) and find the offense that is most common in that ward and shift

In [113]:
#again using that syntax that tells you you are doing multiple methods on teh aggregation of offense
#common_ward_shift = df.groupby(["WARD", "SHIFT"].agg({"OFFENSE": lambda x: x.value_counts(sort = True, ascending = False).index[0]}).reset_index()

##ANSWER
common_ward_shift2 = df.groupby(["WARD","SHIFT"]).agg({"OFFENSE": lambda x: x.mode()})

print(common_ward_shift2)

                                  OFFENSE
WARD SHIFT
1    DAY                      THEFT/OTHER
     EVENING                  THEFT/OTHER
     MIDNIGHT                 THEFT/OTHER
2    DAY                      THEFT/OTHER
     EVENING                  THEFT/OTHER
     MIDNIGHT                 THEFT/OTHER
3    DAY                      THEFT/OTHER
     EVENING                  THEFT/OTHER
     MIDNIGHT                 THEFT/OTHER
4    DAY                     THEFT F/AUTO
     EVENING                  THEFT/OTHER
     MIDNIGHT                 THEFT/OTHER
5    DAY                     THEFT F/AUTO
     EVENING                  THEFT/OTHER
     MIDNIGHT                 THEFT/OTHER
6    DAY                      THEFT/OTHER
     EVENING                  THEFT/OTHER
     MIDNIGHT                 THEFT/OTHER
7    DAY                     THEFT F/AUTO
     EVENING                  THEFT/OTHER
     MIDNIGHT                 THEFT/OTHER
8    DAY                     THEFT F/AUTO
     EVENING                  THEFT/OTHER
     MIDNIGHT  ASSAULT W/DANGEROUS WEAPON

In [121]:
##EXAMPLES BEFORE NEXT SECTIOn

df[df.X > -76] #way to filter it

## RECODING
## use np.select() when you have many conditions, and you can also give it a default
## you can also give it a dictionary to map one thing to another

,X,Y,CCN,REPORT_DAT,SHIFT,METHOD,OFFENSE,BLOCK,XBLOCK,YBLOCK,...,BLOCK_GROUP,CENSUS_TRACT,VOTING_PRECINCT,LATITUDE,LONGITUDE,BID,START_DATE,END_DATE,OBJECTID,OCTO_RECORD_ID
0,23.012460,38.903968,20008120,2020/01/14 15:49:55+00,DAY,OTHERS,THEFT F/AUTO,1200 - 1299 BLOCK OF NEAL STREET NE,401081.0,137345.0,...,008802 3,8802.0,Precinct 77,38.903960,-76.987537,NaN,2020/01/14 15:04:04+00,NaN,673713315,NaN
1,22.995160,38.833739,20008192,2020/01/14 19:43:04+00,DAY,GUN,ASSAULT W/DANGEROUS WEAPON,100 - 165 BLOCK OF MISSISSIPPI AVENUE SE,399580.0,129549.0,...,009803 3,9803.0,Precinct 124,38.833731,-77.004837,NaN,2020/01/14 17:17:37+00,NaN,673713316,NaN
2,23.000528,38.907644,20008246,2020/01/14 20:09:52+00,EVENING,OTHERS,THEFT/OTHER,400 - 499 BLOCK OF MORSE STREET NE,400046.0,137753.0,...,008803 2,8803.0,Precinct 76,38.907636,-76.999470,NaN,2020/01/10 23:00:00+00,2020/01/14 18:00:44+00,673713317,NaN
3,23.017271,38.916480,20008501,2020/01/15 03:28:53+00,EVENING,OTHERS,THEFT/OTHER,1500 - 1599 BLOCK OF NEW YORK AVENUE NE,401498.0,138734.0,...,008803 1,8803.0,Precinct 76,38.916472,-76.982727,NaN,2020/01/15 02:31:24+00,NaN,673713318,NaN
4,23.019923,38.917191,20009148,2020/01/16 04:12:47+00,MIDNIGHT,OTHERS,THEFT/OTHER,1600 - 1779 BLOCK OF NEW YORK AVENUE NE,401728.0,138813.0,...,008803 1,8803.0,Precinct 76,38.917184,-76.980074,NaN,2020/01/16 01:15:36+00,2020/01/16 01:19:54+00,673713319,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27926,22.900569,38.923051,20031083,2020/02/20 22:41:51+00,EVENING,OTHERS,THEFT/OTHER,5000 - 5099 BLOCK OF MACARTHUR COURT NW,391378.0,139468.0,...,000902 1,902.0,Precinct 8,38.923043,-77.099428,NaN,2020/02/13 21:07:38+00,2020/02/20 12:00:55+00,674255559,NaN
27927,23.005634,38.886033,20105472,2020/07/23 20:01:57+00,EVENING,OTHERS,THEFT F/AUTO,800 - 899 BLOCK OF C STREET SE,400489.0,135354.0,...,006600 2,6600.0,Precinct 89,38.886025,-76.994364,CAPITOL HILL,2020/07/22 20:00:24+00,2020/07/22 20:15:36+00,674255577,NaN
27928,23.029624,38.896659,20118027,2020/08/18 20:21:23+00,EVENING,OTHERS,THEFT/OTHER,500 - 599 BLOCK OF OKLAHOMA AVENUE NE,402570.0,136534.0,...,006804 1,6804.0,Precinct 80,38.896651,-76.970374,NaN,2020/08/17 16:00:10+00,2020/08/18 19:30:53+00,674255586,NaN
27929,22.940778,38.926646,20401320,2020/09/05 19:49:00+00,EVENING,OTHERS,THEFT/OTHER,2910 - 2999 BLOCK OF GARFIELD STREET NW,394865.0,139864.0,...,000502 1,502.0,Precinct 26,38.926638,-77.059219,NaN,2020/09/04 22:00:00+00,2020/09/05 13:00:00+00,674255588,NaN
27930,22.970368,38.906451,20089385,2020/06/17 18:01:07+00,DAY,OTHERS,THEFT F/AUTO,1200 - 1299 BLOCK OF 13TH STREET NW,397430.0,137621.0,...,005003 2,5003.0,Precinct 17,38.906444,-77.029630,NaN,2020/06/17 13:25:24+00,2020/06/17 13:45:33+00,674255589,NaN

## Summarizing over all rows or all columns (without grouping)

We can also use the `apply` function to summarize rows or columns efficiently

**Task**: find the mean lat and longitude in one line of code

In [69]:
LL_mean_df = df[["LATITUDE", "LONGITUDE"]].apply("mean", axis = 0)
## double square brackets are used for selecting multiple columns
## axis = 0 to apply it down through the columns

print(LL_mean_df)

LATITUDE     38.907610
LONGITUDE   -77.007047
dtype: float64

## 2. Creating new columns/transforming their type

### Simple filtering

`np.where` is in the numpy package (aliased as `np`) and operates similar to `ifelse` in R

But there is a built in pandas way to emulate this.

**Task**: create an indicator `is_theft` for any offense that contains the word "THEFT"
    
**Task**: create an indicator `is_theft_notmotor` for any offense that contains the word "THEFT" but does not contain the word "MOTOR"

In [71]:
#indicator is new column
df["is_theft"] = np.where(df.OFFENSE.str.contains("THEFT"), True, False)
df
df["is_theft_notmotor"] = np.where(df.OFFENSE.str.contains("THEFT") &
                                   ~df.OFFENSE.str.contains("MOTOR"),
                                   True, False)
df
#~ is pandas version of ! in R (like a NOT operator i suppose)

## the default is already True so don't necessarily need np.where
##-->MOST DIRECT SOLUTION = 
df["OFFENSE"].str.contains("THEFT") & ~df.OFFENSE.str.contains("MOTOR")

,X,Y,CCN,REPORT_DAT,SHIFT,METHOD,OFFENSE,BLOCK,XBLOCK,YBLOCK,...,LONGITUDE,BID,START_DATE,END_DATE,OBJECTID,OCTO_RECORD_ID,SHIFTS,OFFENSE_NOSP,START_DATE_CLEAN,is_theft
0,-76.987540,38.903968,20008120,2020/01/14 15:49:55+00,daytime,OTHERS,THEFT F/AUTO,1200 - 1299 BLOCK OF NEAL STREET NE,401081.0,137345.0,...,-76.987537,NaN,2020/01/14 15:04:04+00,NaN,673713315,NaN,daytime,THEFT_F/AUTO,2020-01-14 15:04:04+00:00,True
1,-77.004840,38.833739,20008192,2020/01/14 19:43:04+00,daytime,GUN,ASSAULT W/DANGEROUS WEAPON,100 - 165 BLOCK OF MISSISSIPPI AVENUE SE,399580.0,129549.0,...,-77.004837,NaN,2020/01/14 17:17:37+00,NaN,673713316,NaN,daytime,ASSAULT_W/DANGEROUS_WEAPON,2020-01-14 17:17:37+00:00,False
2,-76.999472,38.907644,20008246,2020/01/14 20:09:52+00,daytime,OTHERS,THEFT/OTHER,400 - 499 BLOCK OF MORSE STREET NE,400046.0,137753.0,...,-76.999470,NaN,2020/01/10 23:00:00+00,2020/01/14 18:00:44+00,673713317,NaN,nighttime,THEFT/OTHER,2020-01-10 23:00:00+00:00,True
3,-76.982729,38.916480,20008501,2020/01/15 03:28:53+00,daytime,OTHERS,THEFT/OTHER,1500 - 1599 BLOCK OF NEW YORK AVENUE NE,401498.0,138734.0,...,-76.982727,NaN,2020/01/15 02:31:24+00,NaN,673713318,NaN,nighttime,THEFT/OTHER,2020-01-15 02:31:24+00:00,True
4,-76.980077,38.917191,20009148,2020/01/16 04:12:47+00,daytime,OTHERS,THEFT/OTHER,1600 - 1779 BLOCK OF NEW YORK AVENUE NE,401728.0,138813.0,...,-76.980074,NaN,2020/01/16 01:15:36+00,2020/01/16 01:19:54+00,673713319,NaN,nighttime,THEFT/OTHER,2020-01-16 01:15:36+00:00,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27926,-77.099431,38.923051,20031083,2020/02/20 22:41:51+00,daytime,OTHERS,THEFT/OTHER,5000 - 5099 BLOCK OF MACARTHUR COURT NW,391378.0,139468.0,...,-77.099428,NaN,2020/02/13 21:07:38+00,2020/02/20 12:00:55+00,674255559,NaN,nighttime,THEFT/OTHER,2020-02-13 21:07:38+00:00,True
27927,-76.994366,38.886033,20105472,2020/07/23 20:01:57+00,daytime,OTHERS,THEFT F/AUTO,800 - 899 BLOCK OF C STREET SE,400489.0,135354.0,...,-76.994364,CAPITOL HILL,2020/07/22 20:00:24+00,2020/07/22 20:15:36+00,674255577,NaN,nighttime,THEFT_F/AUTO,2020-07-22 20:00:24+00:00,True
27928,-76.970376,38.896659,20118027,2020/08/18 20:21:23+00,daytime,OTHERS,THEFT/OTHER,500 - 599 BLOCK OF OKLAHOMA AVENUE NE,402570.0,136534.0,...,-76.970374,NaN,2020/08/17 16:00:10+00,2020/08/18 19:30:53+00,674255586,NaN,nighttime,THEFT/OTHER,2020-08-17 16:00:10+00:00,True
27929,-77.059222,38.926646,20401320,2020/09/05 19:49:00+00,daytime,OTHERS,THEFT/OTHER,2910 - 2999 BLOCK OF GARFIELD STREET NW,394865.0,139864.0,...,-77.059219,NaN,2020/09/04 22:00:00+00,2020/09/05 13:00:00+00,674255588,NaN,nighttime,THEFT/OTHER,2020-09-04 22:00:00+00:00,True
27930,-77.029632,38.906451,20089385,2020/06/17 18:01:07+00,daytime,OTHERS,THEFT F/AUTO,1200 - 1299 BLOCK OF 13TH STREET NW,397430.0,137621.0,...,-77.029630,NaN,2020/06/17 13:25:24+00,2020/06/17 13:45:33+00,674255589,NaN,daytime,THEFT_F/AUTO,2020-06-17 13:25:24+00:00,True

,X,Y,CCN,REPORT_DAT,SHIFT,METHOD,OFFENSE,BLOCK,XBLOCK,YBLOCK,...,BID,START_DATE,END_DATE,OBJECTID,OCTO_RECORD_ID,SHIFTS,OFFENSE_NOSP,START_DATE_CLEAN,is_theft,is_theft_notmotor
0,-76.987540,38.903968,20008120,2020/01/14 15:49:55+00,daytime,OTHERS,THEFT F/AUTO,1200 - 1299 BLOCK OF NEAL STREET NE,401081.0,137345.0,...,NaN,2020/01/14 15:04:04+00,NaN,673713315,NaN,daytime,THEFT_F/AUTO,2020-01-14 15:04:04+00:00,True,True
1,-77.004840,38.833739,20008192,2020/01/14 19:43:04+00,daytime,GUN,ASSAULT W/DANGEROUS WEAPON,100 - 165 BLOCK OF MISSISSIPPI AVENUE SE,399580.0,129549.0,...,NaN,2020/01/14 17:17:37+00,NaN,673713316,NaN,daytime,ASSAULT_W/DANGEROUS_WEAPON,2020-01-14 17:17:37+00:00,False,False
2,-76.999472,38.907644,20008246,2020/01/14 20:09:52+00,daytime,OTHERS,THEFT/OTHER,400 - 499 BLOCK OF MORSE STREET NE,400046.0,137753.0,...,NaN,2020/01/10 23:00:00+00,2020/01/14 18:00:44+00,673713317,NaN,nighttime,THEFT/OTHER,2020-01-10 23:00:00+00:00,True,True
3,-76.982729,38.916480,20008501,2020/01/15 03:28:53+00,daytime,OTHERS,THEFT/OTHER,1500 - 1599 BLOCK OF NEW YORK AVENUE NE,401498.0,138734.0,...,NaN,2020/01/15 02:31:24+00,NaN,673713318,NaN,nighttime,THEFT/OTHER,2020-01-15 02:31:24+00:00,True,True
4,-76.980077,38.917191,20009148,2020/01/16 04:12:47+00,daytime,OTHERS,THEFT/OTHER,1600 - 1779 BLOCK OF NEW YORK AVENUE NE,401728.0,138813.0,...,NaN,2020/01/16 01:15:36+00,2020/01/16 01:19:54+00,673713319,NaN,nighttime,THEFT/OTHER,2020-01-16 01:15:36+00:00,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27926,-77.099431,38.923051,20031083,2020/02/20 22:41:51+00,daytime,OTHERS,THEFT/OTHER,5000 - 5099 BLOCK OF MACARTHUR COURT NW,391378.0,139468.0,...,NaN,2020/02/13 21:07:38+00,2020/02/20 12:00:55+00,674255559,NaN,nighttime,THEFT/OTHER,2020-02-13 21:07:38+00:00,True,True
27927,-76.994366,38.886033,20105472,2020/07/23 20:01:57+00,daytime,OTHERS,THEFT F/AUTO,800 - 899 BLOCK OF C STREET SE,400489.0,135354.0,...,CAPITOL HILL,2020/07/22 20:00:24+00,2020/07/22 20:15:36+00,674255577,NaN,nighttime,THEFT_F/AUTO,2020-07-22 20:00:24+00:00,True,True
27928,-76.970376,38.896659,20118027,2020/08/18 20:21:23+00,daytime,OTHERS,THEFT/OTHER,500 - 599 BLOCK OF OKLAHOMA AVENUE NE,402570.0,136534.0,...,NaN,2020/08/17 16:00:10+00,2020/08/18 19:30:53+00,674255586,NaN,nighttime,THEFT/OTHER,2020-08-17 16:00:10+00:00,True,True
27929,-77.059222,38.926646,20401320,2020/09/05 19:49:00+00,daytime,OTHERS,THEFT/OTHER,2910 - 2999 BLOCK OF GARFIELD STREET NW,394865.0,139864.0,...,NaN,2020/09/04 22:00:00+00,2020/09/05 13:00:00+00,674255588,NaN,nighttime,THEFT/OTHER,2020-09-04 22:00:00+00:00,True,True
27930,-77.029632,38.906451,20089385,2020/06/17 18:01:07+00,daytime,OTHERS,THEFT F/AUTO,1200 - 1299 BLOCK OF 13TH STREET NW,397430.0,137621.0,...,NaN,2020/06/17 13:25:24+00,2020/06/17 13:45:33+00,674255589,NaN,daytime,THEFT_F/AUTO,2020-06-17 13:25:24+00:00,True,True

0         True
1        False
2         True
3         True
4         True
         ...
27926     True
27927     True
27928     True
27929     True
27930     True
Name: OFFENSE, Length: 27931, dtype: bool

### np.select

**Task**: create a new variable, `offense_summary`, where you:
        
- Recode theft offenses that use a gun or knife as the method (`METHOD`) as: violent theft
- Recode non-theft offenses that use a gun or knife as the method as: violent other
- Recode all other as non-violent

In [73]:
cats = ["violent theft", "violent other"]

conditions = [
    df["is_theft"] & df["METHOD"].isin(["GUN", "KNIFE"]),
    ~df["is_theft"] & df["METHOD"].isin(["GUN", "KNIFE"])   
]


df["offense_summary"] = np.select(conditions, cats, default = "non-violent")

df

,X,Y,CCN,REPORT_DAT,SHIFT,METHOD,OFFENSE,BLOCK,XBLOCK,YBLOCK,...,START_DATE,END_DATE,OBJECTID,OCTO_RECORD_ID,SHIFTS,OFFENSE_NOSP,START_DATE_CLEAN,is_theft,is_theft_notmotor,offense_summary
0,-76.987540,38.903968,20008120,2020/01/14 15:49:55+00,daytime,OTHERS,THEFT F/AUTO,1200 - 1299 BLOCK OF NEAL STREET NE,401081.0,137345.0,...,2020/01/14 15:04:04+00,NaN,673713315,NaN,daytime,THEFT_F/AUTO,2020-01-14 15:04:04+00:00,True,True,non-violent
1,-77.004840,38.833739,20008192,2020/01/14 19:43:04+00,daytime,GUN,ASSAULT W/DANGEROUS WEAPON,100 - 165 BLOCK OF MISSISSIPPI AVENUE SE,399580.0,129549.0,...,2020/01/14 17:17:37+00,NaN,673713316,NaN,daytime,ASSAULT_W/DANGEROUS_WEAPON,2020-01-14 17:17:37+00:00,False,False,violent other
2,-76.999472,38.907644,20008246,2020/01/14 20:09:52+00,daytime,OTHERS,THEFT/OTHER,400 - 499 BLOCK OF MORSE STREET NE,400046.0,137753.0,...,2020/01/10 23:00:00+00,2020/01/14 18:00:44+00,673713317,NaN,nighttime,THEFT/OTHER,2020-01-10 23:00:00+00:00,True,True,non-violent
3,-76.982729,38.916480,20008501,2020/01/15 03:28:53+00,daytime,OTHERS,THEFT/OTHER,1500 - 1599 BLOCK OF NEW YORK AVENUE NE,401498.0,138734.0,...,2020/01/15 02:31:24+00,NaN,673713318,NaN,nighttime,THEFT/OTHER,2020-01-15 02:31:24+00:00,True,True,non-violent
4,-76.980077,38.917191,20009148,2020/01/16 04:12:47+00,daytime,OTHERS,THEFT/OTHER,1600 - 1779 BLOCK OF NEW YORK AVENUE NE,401728.0,138813.0,...,2020/01/16 01:15:36+00,2020/01/16 01:19:54+00,673713319,NaN,nighttime,THEFT/OTHER,2020-01-16 01:15:36+00:00,True,True,non-violent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27926,-77.099431,38.923051,20031083,2020/02/20 22:41:51+00,daytime,OTHERS,THEFT/OTHER,5000 - 5099 BLOCK OF MACARTHUR COURT NW,391378.0,139468.0,...,2020/02/13 21:07:38+00,2020/02/20 12:00:55+00,674255559,NaN,nighttime,THEFT/OTHER,2020-02-13 21:07:38+00:00,True,True,non-violent
27927,-76.994366,38.886033,20105472,2020/07/23 20:01:57+00,daytime,OTHERS,THEFT F/AUTO,800 - 899 BLOCK OF C STREET SE,400489.0,135354.0,...,2020/07/22 20:00:24+00,2020/07/22 20:15:36+00,674255577,NaN,nighttime,THEFT_F/AUTO,2020-07-22 20:00:24+00:00,True,True,non-violent
27928,-76.970376,38.896659,20118027,2020/08/18 20:21:23+00,daytime,OTHERS,THEFT/OTHER,500 - 599 BLOCK OF OKLAHOMA AVENUE NE,402570.0,136534.0,...,2020/08/17 16:00:10+00,2020/08/18 19:30:53+00,674255586,NaN,nighttime,THEFT/OTHER,2020-08-17 16:00:10+00:00,True,True,non-violent
27929,-77.059222,38.926646,20401320,2020/09/05 19:49:00+00,daytime,OTHERS,THEFT/OTHER,2910 - 2999 BLOCK OF GARFIELD STREET NW,394865.0,139864.0,...,2020/09/04 22:00:00+00,2020/09/05 13:00:00+00,674255588,NaN,nighttime,THEFT/OTHER,2020-09-04 22:00:00+00:00,True,True,non-violent
27930,-77.029632,38.906451,20089385,2020/06/17 18:01:07+00,daytime,OTHERS,THEFT F/AUTO,1200 - 1299 BLOCK OF 13TH STREET NW,397430.0,137621.0,...,2020/06/17 13:25:24+00,2020/06/17 13:45:33+00,674255589,NaN,daytime,THEFT_F/AUTO,2020-06-17 13:25:24+00:00,True,True,non-violent

### map.recode

**Task**: recode shifts that are MIDNIGHT or EVENING as "nighttime"; code other shift to daytime

In [59]:
df

cats = ["nighttime"]

conditions = [
    df.SHIFT.isin(["MIDNIGHT", "EVENING"])
]

df["SHIFT"] = np.select(conditions, cats, default = "daytime")


## OTHER WAY TO DO IT
shifts = ["EVENING", "DAY", "MIDNIGHT"]
time = ["nighttime", "daytime", "nighttime"]


conversion_dict = dict(zip(time, shifts))
df.SHIFT.map(conversion_dict)

df

,X,Y,CCN,REPORT_DAT,SHIFT,METHOD,OFFENSE,BLOCK,XBLOCK,YBLOCK,...,LATITUDE,LONGITUDE,BID,START_DATE,END_DATE,OBJECTID,OCTO_RECORD_ID,SHIFTS,OFFENSE_NOSP,START_DATE_CLEAN
0,-76.987540,38.903968,20008120,2020/01/14 15:49:55+00,daytime,OTHERS,THEFT F/AUTO,1200 - 1299 BLOCK OF NEAL STREET NE,401081.0,137345.0,...,38.903960,-76.987537,NaN,2020/01/14 15:04:04+00,NaN,673713315,NaN,daytime,THEFT_F/AUTO,2020-01-14 15:04:04+00:00
1,-77.004840,38.833739,20008192,2020/01/14 19:43:04+00,daytime,GUN,ASSAULT W/DANGEROUS WEAPON,100 - 165 BLOCK OF MISSISSIPPI AVENUE SE,399580.0,129549.0,...,38.833731,-77.004837,NaN,2020/01/14 17:17:37+00,NaN,673713316,NaN,daytime,ASSAULT_W/DANGEROUS_WEAPON,2020-01-14 17:17:37+00:00
2,-76.999472,38.907644,20008246,2020/01/14 20:09:52+00,daytime,OTHERS,THEFT/OTHER,400 - 499 BLOCK OF MORSE STREET NE,400046.0,137753.0,...,38.907636,-76.999470,NaN,2020/01/10 23:00:00+00,2020/01/14 18:00:44+00,673713317,NaN,nighttime,THEFT/OTHER,2020-01-10 23:00:00+00:00
3,-76.982729,38.916480,20008501,2020/01/15 03:28:53+00,daytime,OTHERS,THEFT/OTHER,1500 - 1599 BLOCK OF NEW YORK AVENUE NE,401498.0,138734.0,...,38.916472,-76.982727,NaN,2020/01/15 02:31:24+00,NaN,673713318,NaN,nighttime,THEFT/OTHER,2020-01-15 02:31:24+00:00
4,-76.980077,38.917191,20009148,2020/01/16 04:12:47+00,daytime,OTHERS,THEFT/OTHER,1600 - 1779 BLOCK OF NEW YORK AVENUE NE,401728.0,138813.0,...,38.917184,-76.980074,NaN,2020/01/16 01:15:36+00,2020/01/16 01:19:54+00,673713319,NaN,nighttime,THEFT/OTHER,2020-01-16 01:15:36+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27926,-77.099431,38.923051,20031083,2020/02/20 22:41:51+00,daytime,OTHERS,THEFT/OTHER,5000 - 5099 BLOCK OF MACARTHUR COURT NW,391378.0,139468.0,...,38.923043,-77.099428,NaN,2020/02/13 21:07:38+00,2020/02/20 12:00:55+00,674255559,NaN,nighttime,THEFT/OTHER,2020-02-13 21:07:38+00:00
27927,-76.994366,38.886033,20105472,2020/07/23 20:01:57+00,daytime,OTHERS,THEFT F/AUTO,800 - 899 BLOCK OF C STREET SE,400489.0,135354.0,...,38.886025,-76.994364,CAPITOL HILL,2020/07/22 20:00:24+00,2020/07/22 20:15:36+00,674255577,NaN,nighttime,THEFT_F/AUTO,2020-07-22 20:00:24+00:00
27928,-76.970376,38.896659,20118027,2020/08/18 20:21:23+00,daytime,OTHERS,THEFT/OTHER,500 - 599 BLOCK OF OKLAHOMA AVENUE NE,402570.0,136534.0,...,38.896651,-76.970374,NaN,2020/08/17 16:00:10+00,2020/08/18 19:30:53+00,674255586,NaN,nighttime,THEFT/OTHER,2020-08-17 16:00:10+00:00
27929,-77.059222,38.926646,20401320,2020/09/05 19:49:00+00,daytime,OTHERS,THEFT/OTHER,2910 - 2999 BLOCK OF GARFIELD STREET NW,394865.0,139864.0,...,38.926638,-77.059219,NaN,2020/09/04 22:00:00+00,2020/09/05 13:00:00+00,674255588,NaN,nighttime,THEFT/OTHER,2020-09-04 22:00:00+00:00
27930,-77.029632,38.906451,20089385,2020/06/17 18:01:07+00,daytime,OTHERS,THEFT F/AUTO,1200 - 1299 BLOCK OF 13TH STREET NW,397430.0,137621.0,...,38.906444,-77.029630,NaN,2020/06/17 13:25:24+00,2020/06/17 13:45:33+00,674255589,NaN,daytime,THEFT_F/AUTO,2020-06-17 13:25:24+00:00

0        DAY
1        DAY
2        DAY
3        DAY
4        DAY
        ...
27926    DAY
27927    DAY
27928    DAY
27929    DAY
27930    DAY
Name: SHIFT, Length: 27931, dtype: object

,X,Y,CCN,REPORT_DAT,SHIFT,METHOD,OFFENSE,BLOCK,XBLOCK,YBLOCK,...,LATITUDE,LONGITUDE,BID,START_DATE,END_DATE,OBJECTID,OCTO_RECORD_ID,SHIFTS,OFFENSE_NOSP,START_DATE_CLEAN
0,-76.987540,38.903968,20008120,2020/01/14 15:49:55+00,daytime,OTHERS,THEFT F/AUTO,1200 - 1299 BLOCK OF NEAL STREET NE,401081.0,137345.0,...,38.903960,-76.987537,NaN,2020/01/14 15:04:04+00,NaN,673713315,NaN,daytime,THEFT_F/AUTO,2020-01-14 15:04:04+00:00
1,-77.004840,38.833739,20008192,2020/01/14 19:43:04+00,daytime,GUN,ASSAULT W/DANGEROUS WEAPON,100 - 165 BLOCK OF MISSISSIPPI AVENUE SE,399580.0,129549.0,...,38.833731,-77.004837,NaN,2020/01/14 17:17:37+00,NaN,673713316,NaN,daytime,ASSAULT_W/DANGEROUS_WEAPON,2020-01-14 17:17:37+00:00
2,-76.999472,38.907644,20008246,2020/01/14 20:09:52+00,daytime,OTHERS,THEFT/OTHER,400 - 499 BLOCK OF MORSE STREET NE,400046.0,137753.0,...,38.907636,-76.999470,NaN,2020/01/10 23:00:00+00,2020/01/14 18:00:44+00,673713317,NaN,nighttime,THEFT/OTHER,2020-01-10 23:00:00+00:00
3,-76.982729,38.916480,20008501,2020/01/15 03:28:53+00,daytime,OTHERS,THEFT/OTHER,1500 - 1599 BLOCK OF NEW YORK AVENUE NE,401498.0,138734.0,...,38.916472,-76.982727,NaN,2020/01/15 02:31:24+00,NaN,673713318,NaN,nighttime,THEFT/OTHER,2020-01-15 02:31:24+00:00
4,-76.980077,38.917191,20009148,2020/01/16 04:12:47+00,daytime,OTHERS,THEFT/OTHER,1600 - 1779 BLOCK OF NEW YORK AVENUE NE,401728.0,138813.0,...,38.917184,-76.980074,NaN,2020/01/16 01:15:36+00,2020/01/16 01:19:54+00,673713319,NaN,nighttime,THEFT/OTHER,2020-01-16 01:15:36+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27926,-77.099431,38.923051,20031083,2020/02/20 22:41:51+00,daytime,OTHERS,THEFT/OTHER,5000 - 5099 BLOCK OF MACARTHUR COURT NW,391378.0,139468.0,...,38.923043,-77.099428,NaN,2020/02/13 21:07:38+00,2020/02/20 12:00:55+00,674255559,NaN,nighttime,THEFT/OTHER,2020-02-13 21:07:38+00:00
27927,-76.994366,38.886033,20105472,2020/07/23 20:01:57+00,daytime,OTHERS,THEFT F/AUTO,800 - 899 BLOCK OF C STREET SE,400489.0,135354.0,...,38.886025,-76.994364,CAPITOL HILL,2020/07/22 20:00:24+00,2020/07/22 20:15:36+00,674255577,NaN,nighttime,THEFT_F/AUTO,2020-07-22 20:00:24+00:00
27928,-76.970376,38.896659,20118027,2020/08/18 20:21:23+00,daytime,OTHERS,THEFT/OTHER,500 - 599 BLOCK OF OKLAHOMA AVENUE NE,402570.0,136534.0,...,38.896651,-76.970374,NaN,2020/08/17 16:00:10+00,2020/08/18 19:30:53+00,674255586,NaN,nighttime,THEFT/OTHER,2020-08-17 16:00:10+00:00
27929,-77.059222,38.926646,20401320,2020/09/05 19:49:00+00,daytime,OTHERS,THEFT/OTHER,2910 - 2999 BLOCK OF GARFIELD STREET NW,394865.0,139864.0,...,38.926638,-77.059219,NaN,2020/09/04 22:00:00+00,2020/09/05 13:00:00+00,674255588,NaN,nighttime,THEFT/OTHER,2020-09-04 22:00:00+00:00
27930,-77.029632,38.906451,20089385,2020/06/17 18:01:07+00,daytime,OTHERS,THEFT F/AUTO,1200 - 1299 BLOCK OF 13TH STREET NW,397430.0,137621.0,...,38.906444,-77.029630,NaN,2020/06/17 13:25:24+00,2020/06/17 13:45:33+00,674255589,NaN,daytime,THEFT_F/AUTO,2020-06-17 13:25:24+00:00

### Using built-in pandas methods

Another way of creating variables, used either alone or in combination with np.where and np.select is to use pandas built in `str` methods

Basic structure is: `df['namestringcol'].str.someoperation`

**Task**: using a `str` method, create a new variable--`OFFENSE_NOSP`--that replaces spaces in the `OFFENSE` column with underscores

In [31]:
df["OFFENSE_NOSP"] = df["OFFENSE"].str.replace(" ", "_")

df

#if before were just looking and testing
df.OFFENSE.iloc[1].replace(" ", "")

,X,Y,CCN,REPORT_DAT,SHIFT,METHOD,OFFENSE,BLOCK,XBLOCK,YBLOCK,...,VOTING_PRECINCT,LATITUDE,LONGITUDE,BID,START_DATE,END_DATE,OBJECTID,OCTO_RECORD_ID,SHIFTS,OFFENSE_NOSP
0,-76.987540,38.903968,20008120,2020/01/14 15:49:55+00,daytime,OTHERS,THEFT F/AUTO,1200 - 1299 BLOCK OF NEAL STREET NE,401081.0,137345.0,...,Precinct 77,38.903960,-76.987537,NaN,2020/01/14 15:04:04+00,NaN,673713315,NaN,daytime,THEFT_F/AUTO
1,-77.004840,38.833739,20008192,2020/01/14 19:43:04+00,daytime,GUN,ASSAULT W/DANGEROUS WEAPON,100 - 165 BLOCK OF MISSISSIPPI AVENUE SE,399580.0,129549.0,...,Precinct 124,38.833731,-77.004837,NaN,2020/01/14 17:17:37+00,NaN,673713316,NaN,daytime,ASSAULT_W/DANGEROUS_WEAPON
2,-76.999472,38.907644,20008246,2020/01/14 20:09:52+00,daytime,OTHERS,THEFT/OTHER,400 - 499 BLOCK OF MORSE STREET NE,400046.0,137753.0,...,Precinct 76,38.907636,-76.999470,NaN,2020/01/10 23:00:00+00,2020/01/14 18:00:44+00,673713317,NaN,nighttime,THEFT/OTHER
3,-76.982729,38.916480,20008501,2020/01/15 03:28:53+00,daytime,OTHERS,THEFT/OTHER,1500 - 1599 BLOCK OF NEW YORK AVENUE NE,401498.0,138734.0,...,Precinct 76,38.916472,-76.982727,NaN,2020/01/15 02:31:24+00,NaN,673713318,NaN,nighttime,THEFT/OTHER
4,-76.980077,38.917191,20009148,2020/01/16 04:12:47+00,daytime,OTHERS,THEFT/OTHER,1600 - 1779 BLOCK OF NEW YORK AVENUE NE,401728.0,138813.0,...,Precinct 76,38.917184,-76.980074,NaN,2020/01/16 01:15:36+00,2020/01/16 01:19:54+00,673713319,NaN,nighttime,THEFT/OTHER
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27926,-77.099431,38.923051,20031083,2020/02/20 22:41:51+00,daytime,OTHERS,THEFT/OTHER,5000 - 5099 BLOCK OF MACARTHUR COURT NW,391378.0,139468.0,...,Precinct 8,38.923043,-77.099428,NaN,2020/02/13 21:07:38+00,2020/02/20 12:00:55+00,674255559,NaN,nighttime,THEFT/OTHER
27927,-76.994366,38.886033,20105472,2020/07/23 20:01:57+00,daytime,OTHERS,THEFT F/AUTO,800 - 899 BLOCK OF C STREET SE,400489.0,135354.0,...,Precinct 89,38.886025,-76.994364,CAPITOL HILL,2020/07/22 20:00:24+00,2020/07/22 20:15:36+00,674255577,NaN,nighttime,THEFT_F/AUTO
27928,-76.970376,38.896659,20118027,2020/08/18 20:21:23+00,daytime,OTHERS,THEFT/OTHER,500 - 599 BLOCK OF OKLAHOMA AVENUE NE,402570.0,136534.0,...,Precinct 80,38.896651,-76.970374,NaN,2020/08/17 16:00:10+00,2020/08/18 19:30:53+00,674255586,NaN,nighttime,THEFT/OTHER
27929,-77.059222,38.926646,20401320,2020/09/05 19:49:00+00,daytime,OTHERS,THEFT/OTHER,2910 - 2999 BLOCK OF GARFIELD STREET NW,394865.0,139864.0,...,Precinct 26,38.926638,-77.059219,NaN,2020/09/04 22:00:00+00,2020/09/05 13:00:00+00,674255588,NaN,nighttime,THEFT/OTHER
27930,-77.029632,38.906451,20089385,2020/06/17 18:01:07+00,daytime,OTHERS,THEFT F/AUTO,1200 - 1299 BLOCK OF 13TH STREET NW,397430.0,137621.0,...,Precinct 17,38.906444,-77.029630,NaN,2020/06/17 13:25:24+00,2020/06/17 13:45:33+00,674255589,NaN,daytime,THEFT_F/AUTO

### Transforming column types

**Task**: check the type of the `START_DATE` column

In [112]:
type(df.START_DATE)
# pandas.core.series.Series

type(df.START_DATE.iloc[1])
# str

df.START_DATE.dtype
#dtype('O')
#--> O (capital o) for object

pandas.core.series.Series

str

dtype('O')

**Task**: recast the `START_DATE` column to datetime, calling this `START_DATE_CLEAN`; coerce errors rather than cleaning the string; check the type of that new col

In [49]:
df["START_DATE_CLEAN"] = pd.to_datetime(df["START_DATE"])

df

,X,Y,CCN,REPORT_DAT,SHIFT,METHOD,OFFENSE,BLOCK,XBLOCK,YBLOCK,...,LATITUDE,LONGITUDE,BID,START_DATE,END_DATE,OBJECTID,OCTO_RECORD_ID,SHIFTS,OFFENSE_NOSP,START_DATE_CLEAN
0,-76.987540,38.903968,20008120,2020/01/14 15:49:55+00,daytime,OTHERS,THEFT F/AUTO,1200 - 1299 BLOCK OF NEAL STREET NE,401081.0,137345.0,...,38.903960,-76.987537,NaN,2020/01/14 15:04:04+00,NaN,673713315,NaN,daytime,THEFT_F/AUTO,2020-01-14 15:04:04+00:00
1,-77.004840,38.833739,20008192,2020/01/14 19:43:04+00,daytime,GUN,ASSAULT W/DANGEROUS WEAPON,100 - 165 BLOCK OF MISSISSIPPI AVENUE SE,399580.0,129549.0,...,38.833731,-77.004837,NaN,2020/01/14 17:17:37+00,NaN,673713316,NaN,daytime,ASSAULT_W/DANGEROUS_WEAPON,2020-01-14 17:17:37+00:00
2,-76.999472,38.907644,20008246,2020/01/14 20:09:52+00,daytime,OTHERS,THEFT/OTHER,400 - 499 BLOCK OF MORSE STREET NE,400046.0,137753.0,...,38.907636,-76.999470,NaN,2020/01/10 23:00:00+00,2020/01/14 18:00:44+00,673713317,NaN,nighttime,THEFT/OTHER,2020-01-10 23:00:00+00:00
3,-76.982729,38.916480,20008501,2020/01/15 03:28:53+00,daytime,OTHERS,THEFT/OTHER,1500 - 1599 BLOCK OF NEW YORK AVENUE NE,401498.0,138734.0,...,38.916472,-76.982727,NaN,2020/01/15 02:31:24+00,NaN,673713318,NaN,nighttime,THEFT/OTHER,2020-01-15 02:31:24+00:00
4,-76.980077,38.917191,20009148,2020/01/16 04:12:47+00,daytime,OTHERS,THEFT/OTHER,1600 - 1779 BLOCK OF NEW YORK AVENUE NE,401728.0,138813.0,...,38.917184,-76.980074,NaN,2020/01/16 01:15:36+00,2020/01/16 01:19:54+00,673713319,NaN,nighttime,THEFT/OTHER,2020-01-16 01:15:36+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27926,-77.099431,38.923051,20031083,2020/02/20 22:41:51+00,daytime,OTHERS,THEFT/OTHER,5000 - 5099 BLOCK OF MACARTHUR COURT NW,391378.0,139468.0,...,38.923043,-77.099428,NaN,2020/02/13 21:07:38+00,2020/02/20 12:00:55+00,674255559,NaN,nighttime,THEFT/OTHER,2020-02-13 21:07:38+00:00
27927,-76.994366,38.886033,20105472,2020/07/23 20:01:57+00,daytime,OTHERS,THEFT F/AUTO,800 - 899 BLOCK OF C STREET SE,400489.0,135354.0,...,38.886025,-76.994364,CAPITOL HILL,2020/07/22 20:00:24+00,2020/07/22 20:15:36+00,674255577,NaN,nighttime,THEFT_F/AUTO,2020-07-22 20:00:24+00:00
27928,-76.970376,38.896659,20118027,2020/08/18 20:21:23+00,daytime,OTHERS,THEFT/OTHER,500 - 599 BLOCK OF OKLAHOMA AVENUE NE,402570.0,136534.0,...,38.896651,-76.970374,NaN,2020/08/17 16:00:10+00,2020/08/18 19:30:53+00,674255586,NaN,nighttime,THEFT/OTHER,2020-08-17 16:00:10+00:00
27929,-77.059222,38.926646,20401320,2020/09/05 19:49:00+00,daytime,OTHERS,THEFT/OTHER,2910 - 2999 BLOCK OF GARFIELD STREET NW,394865.0,139864.0,...,38.926638,-77.059219,NaN,2020/09/04 22:00:00+00,2020/09/05 13:00:00+00,674255588,NaN,nighttime,THEFT/OTHER,2020-09-04 22:00:00+00:00
27930,-77.029632,38.906451,20089385,2020/06/17 18:01:07+00,daytime,OTHERS,THEFT F/AUTO,1200 - 1299 BLOCK OF 13TH STREET NW,397430.0,137621.0,...,38.906444,-77.029630,NaN,2020/06/17 13:25:24+00,2020/06/17 13:45:33+00,674255589,NaN,daytime,THEFT_F/AUTO,2020-06-17 13:25:24+00:00

**Task:** print the min and max of `START_DATE_CLEAN`. What happens if you try to do this with `START_DATE`?

In [114]:
df.START_DATE_CLEAN.dt.year

#vs so much harder if not as date type bc you have to do a lambda function to get it

0        2020
1        2020
2        2020
3        2020
4        2020
         ...
27926    2020
27927    2020
27928    2020
27929    2020
27930    2020
Name: START_DATE_CLEAN, Length: 27931, dtype: int32

In [55]:
print(df["START_DATE_CLEAN"].min())
print(df["START_DATE_CLEAN"].max())
#1940-02-17 00:00:16+00:00
#2021-01-01 02:30:21+00:00

#there are problems when the 0s don't exist bc 2 (feb) will be greater than december (12)
#instead of 02 < 12

print(df["START_DATE"].min())
print(df["START_DATE"].max())
#1940/02/17 00:00:16+00
#2021/01/01 02:30:21+00

#when doing this with "START_DATE", it still outputs just looks different there are / instead of - and the times look different

1940-02-17 00:00:16+00:00
2021-01-01 02:30:21+00:00
1940/02/17 00:00:16+00
2021/01/01 02:30:21+00

## 3. Row and column filtering

### Row subsetting

**Task**: filter to crime reports about theft using the `is_theft` definition and that are in ward 3

In [81]:
df[(df.is_theft) & (df.WARD == 3)]

##need the parantheses or else it will try to take df.is_theft and add it to df.WARD and see if that is equal to 3

,X,Y,CCN,REPORT_DAT,SHIFT,METHOD,OFFENSE,BLOCK,XBLOCK,YBLOCK,...,START_DATE,END_DATE,OBJECTID,OCTO_RECORD_ID,SHIFTS,OFFENSE_NOSP,START_DATE_CLEAN,is_theft,is_theft_notmotor,offense_summary
21,-77.073199,38.926863,20060740,2020/04/19 05:54:37+00,daytime,OTHERS,THEFT F/AUTO,2800 - 2899 BLOCK OF WISCONSIN AVENUE NW,393653.0,139889.0,...,2020/04/18 19:25:52+00,2020/04/18 19:31:53+00,673720665,NaN,nighttime,THEFT_F/AUTO,2020-04-18 19:25:52+00:00,True,True,non-violent
32,-77.069073,38.917353,20017305,2020/01/29 12:46:24+00,daytime,OTHERS,THEFT F/AUTO,2001 - 2112 BLOCK OF WISCONSIN AVENUE NW,394010.0,138833.0,...,2020/01/29 04:09:37+00,2020/01/29 10:45:16+00,673714145,NaN,daytime,THEFT_F/AUTO,2020-01-29 04:09:37+00:00,True,True,non-violent
36,-77.063920,38.944876,20001669,2020/01/03 20:32:51+00,daytime,OTHERS,THEFT/OTHER,4200 - 4399 BLOCK OF CONNECTICUT AVENUE NW,394459.0,141888.0,...,2020/01/03 19:51:36+00,NaN,673713219,NaN,nighttime,THEFT/OTHER,2020-01-03 19:51:36+00:00,True,True,non-violent
73,-77.075827,38.947094,20047077,2020/03/18 01:07:16+00,daytime,OTHERS,THEFT F/AUTO,3800 - 3899 BLOCK OF ALTON PLACE NW,393427.0,142135.0,...,2020/03/17 16:00:30+00,2020/03/17 17:00:07+00,673691568,NaN,nighttime,THEFT_F/AUTO,2020-03-17 16:00:30+00:00,True,True,non-violent
110,-77.099873,38.942211,20048137,2020/03/19 19:50:08+00,daytime,OTHERS,THEFT F/AUTO,5000 - 5101 BLOCK OF UPTON STREET NW,391342.0,141595.0,...,2020/03/19 17:00:11+00,2020/03/19 18:30:17+00,673716925,NaN,nighttime,THEFT_F/AUTO,2020-03-19 17:00:11+00:00,True,True,non-violent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27849,-77.057265,38.930854,20400842,2020/06/24 17:19:20+00,daytime,OTHERS,THEFT/OTHER,2700 - 2799 BLOCK OF CORTLAND PLACE NW,395035.0,140331.0,...,2020/06/22 12:00:00+00,2020/06/22 21:00:00+00,674255149,NaN,daytime,THEFT/OTHER,2020-06-22 12:00:00+00:00,True,True,non-violent
27897,-77.086974,38.959040,20059783,2020/04/16 21:22:42+00,daytime,OTHERS,MOTOR VEHICLE THEFT,4400 - 4499 BLOCK OF JENIFER STREET NW,392462.0,143462.0,...,2020/03/28 01:55:01+00,2020/03/28 02:05:22+00,674255394,NaN,nighttime,MOTOR_VEHICLE_THEFT,2020-03-28 01:55:01+00:00,True,False,non-violent
27925,-77.059657,38.937528,20401829,2020/11/15 18:53:56+00,daytime,OTHERS,THEFT/OTHER,3600 - 3699 BLOCK OF CONNECTICUT AVENUE NW,394828.0,141072.0,...,2020/10/31 18:30:00+00,2020/11/08 18:30:00+00,674255554,NaN,daytime,THEFT/OTHER,2020-10-31 18:30:00+00:00,True,True,non-violent
27926,-77.099431,38.923051,20031083,2020/02/20 22:41:51+00,daytime,OTHERS,THEFT/OTHER,5000 - 5099 BLOCK OF MACARTHUR COURT NW,391378.0,139468.0,...,2020/02/13 21:07:38+00,2020/02/20 12:00:55+00,674255559,NaN,nighttime,THEFT/OTHER,2020-02-13 21:07:38+00:00,True,True,non-violent
27929,-77.059222,38.926646,20401320,2020/09/05 19:49:00+00,daytime,OTHERS,THEFT/OTHER,2910 - 2999 BLOCK OF GARFIELD STREET NW,394865.0,139864.0,...,2020/09/04 22:00:00+00,2020/09/05 13:00:00+00,674255588,NaN,nighttime,THEFT/OTHER,2020-09-04 22:00:00+00:00,True,True,non-violent

### Column subsetting

**Task**: select two columns--`START_DATE` and `END_DATE`--and print the head of the dataframe

In [122]:
df[["START_DATE", "END_DATE"]].head()

##remember you need double brackets when selecting two columns

##NaN --> not a number

#also useful bc you can do rows and columns
date_df = df.loc[:, ["START_DATE", "END_DATE"]]

               START_DATE                END_DATE
0  2020/01/14 15:04:04+00                     NaN
1  2020/01/14 17:17:37+00                     NaN
2  2020/01/10 23:00:00+00  2020/01/14 18:00:44+00
3  2020/01/15 02:31:24+00                     NaN
4  2020/01/16 01:15:36+00  2020/01/16 01:19:54+00

**Task**: use list comprehension to automate this a bit and select all columns with the word "DATE" in the name; print the head of the dataframe

In [132]:
df[[c for c in df if "DATE" in c]].head()

#df[[cols for cols in df if "DATE" in cols]].head()

##if wat to add tjings

SyntaxError: invalid syntax (2276264767.py, line 7)

**Task**: filter reports of crime in `START_DATE_CLEAN` before May 2020 and that are located in ward 1; select the ward and `START_DATE` column and print a random sample of rows

In [134]:
df[(df.START_DATE_CLEAN < "2020-05-01") & (df.WARD == 3)].sample(4)

#.sample to get a random sample of 4 rows
#can either do it with (n = 10) to do 10 random lines, OR
# (frac = 0.05) and you get a 5% sample
#if you do (frac = 1), it gives you all of them but RANDOMIZES THE ORDER

#SO YOU USE THAT IF YOU WANT TO SCRAMBLE UR DF

,X,Y,CCN,REPORT_DAT,SHIFT,METHOD,OFFENSE,BLOCK,XBLOCK,YBLOCK,...,START_DATE,END_DATE,OBJECTID,OCTO_RECORD_ID,SHIFTS,OFFENSE_NOSP,START_DATE_CLEAN,is_theft,is_theft_notmotor,offense_summary
9815,-77.056793,38.932601,20005207,2020/01/09 23:08:36+00,daytime,OTHERS,THEFT/OTHER,3200 - 3299 BLOCK OF CONNECTICUT AVENUE NW,395076.0,140525.0,...,2020/01/06 15:26:45+00,2020/01/07 04:06:25+00,673983127,NaN,nighttime,THEFT/OTHER,2020-01-06 15:26:45+00:00,True,True,non-violent
8588,-77.085302,38.959915,20037293,2020/03/02 02:49:51+00,daytime,OTHERS,THEFT/OTHER,5300 - 5399 BLOCK OF WISCONSIN AVENUE NW,392607.0,143559.0,...,2020/03/01 18:07:53+00,2020/03/01 18:36:36+00,673974460,NaN,nighttime,THEFT/OTHER,2020-03-01 18:07:53+00:00,True,True,non-violent
22368,-77.078517,38.948777,20400376,2020/03/18 17:12:55+00,daytime,OTHERS,THEFT/OTHER,4500 - 4599 BLOCK OF FORT DRIVE NW,393194.0,142322.0,...,2020/03/13 20:15:00+00,2020/03/16 16:30:00+00,674203755,NaN,daytime,THEFT/OTHER,2020-03-13 20:15:00+00:00,True,True,non-violent
14049,-77.085302,38.959915,20031346,2020/02/21 07:28:46+00,daytime,OTHERS,THEFT/OTHER,5300 - 5399 BLOCK OF WISCONSIN AVENUE NW,392607.0,143559.0,...,2020/02/21 04:45:02+00,2020/02/21 04:50:12+00,674024473,NaN,nighttime,THEFT/OTHER,2020-02-21 04:45:02+00:00,True,True,non-violent